apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster
  region: us-east-1

vpc:
  subnets:
    private:
      us-east-1a: { id: subnet-d026d49a-replace-me }
      us-east-1b: { id: subnet-fedb3ffg-replace-me }
      us-east-1c: { id: subnet-b50c23eb-replace-me }

nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: t3.small
    desiredCapacity: 2
    privateNetworking: true
  - name: ng-2-builders
    labels: { role: builders }
    instanceType: t3.small
    desiredCapacity: 2
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true